project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!application/" # To avoid running the topic model that was not working for me

website:
  repo-url: https://github.com/tdelcey/becoming_economists
  repo-actions: [source, issue]
  # navbar:
  #   tools:
  #     - icon: github
  #       menu:
  #         - text: Source Code
  #           url:  https://github.com/tdelcey/becoming_economists
  #         - text: Report a Bug
  #           url:  https://github.com/tdelcey/becoming_economists/issues
  #   background: primary
  #   pinned: true 
  #   left:
  #     - text: "Home"
  #       file: index.qmd
  #     - file: documentation.qmd
  #     - file: data.qmd
  #     - file: application.qmd
  #     - file: news.qmd
  page-footer:
   right: 
    - text: "© Thomas Delcey"
      href: https://thomasdelcey.com/
    - text: "Aurelien Goutsmedt"
      href: https://aurelien-goutsmedt.com
      
      
  sidebar:
      logo: "assets/website_logo.png"
      pinned: true
      align: center
      tools: 
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/tdelcey/becoming_economists
          - text: Report a Bug
            url:  https://github.com/tdelcey/becoming_economists/issues
      style: "floating"
      search: true
      collapse-level: 1
      contents: 
        - file: index.qmd
        - file: documentation.qmd
        - file: data.qmd
        # - file: application.qmd
        - file: news.qmd

format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1500px
      margin-width: 200px
      gutter-width: 1.5rem
    theme: litera

